FROM node
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN npm install
RUN npm install -g express
RUN npm install -g nodemon
EXPOSE 3000
CMD [ "node", "/usr/src/app/index.js" ]
